### ISSUE TITLE
the value of traefik_tls_crt

### ISSUE THREAD

**Issue by Zane5** [nemonik/hands-on-DevOps-gen2#4]
Hi nemonik, thanks your book, it's very helpful.

I tried to make my domain certificate, but the firefox show "Warning: Potential Security Risk Ahead"

the wildcard domain keys, `fullchain.pem` and `privkey.pem`:

/etc/letsencrypt/live/example.com/fullchain.pem
```
-----BEGIN CERTIFICATE-----
1xxxxxx
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
2xxxxxx
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
3xxxxxx
-----END CERTIFICATE-----
```
/etc/letsencrypt/live/example.com/privkey.pem
```
-----BEGIN CERTIFICATE-----
4xxxxxx
-----END CERTIFICATE-----
```

I made the `vault` file and got a `traefik-cert-secrets.yaml`:

```
...
data:
  tls.crt: |
    1xxxxxx
  tls.key: |
    4xxxxxx
```

There are 3 keys in fullchain.pem, I don't known the content of `tls.crt` should be (just wrotre the first 1xxxxxx in `tls.crt`).

Thanks for any opinions :)

**Comment by nemonik** [comment]
I need to document this section.

I will write up something today and place in the README.md file.

**Comment by nemonik** [comment]
Updated README.md with the first stab at Let's Encrypt documentation.

**Comment by nemonik** [comment]
i'll continue to tweak the text... i should be using the domain variable throughout the IaC lemme know if not pls...

**Comment by nemonik** [comment]
Can I close? Are things working for you?
